spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mydbinstance2.cmcjn8qqcxqk.ap-northeast-1.rds.amazonaws.com:3306/connectU?serverTimezone=UTC
      username: admin
      password: GBb4ddyE1mfrBFGQA5sc
#=============================================================
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB




# ========================================================================
  #mybatis plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto



#=============================================================

cloud:
  aws:
    credentials:
      access-key: AKIARXOOQM5FKQYNF442
      secret-key: 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
    region:
      static: ap-northeast-1
    stack:
      auto: false

application:
  bucket:
    name: seeiebucket


server:
  servlet:
    session:
      timeout: 3600000
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: connectu
    key-store-type: PKCS12
    key-alias: tomcat

